# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'news app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for news app
  pod 'GoogleSignIn'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'FirebaseFirestore'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'

end
